server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservationSystems/** 
        - id: Management
          uri: http://localhost:8082
          predicates:
            - Path=/hairShopManagementSystems/** /reservationStatuses/**
        - id: CustomerCare
          uri: http://localhost:8083
          predicates:
            - Path= 
        - id: HRSystem
          uri: http://localhost:8084
          predicates:
            - Path=/hrSystems/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Reservation
          uri: http://Reservation:8080
          predicates:
            - Path=/reservationSystems/** 
        - id: Management
          uri: http://Management:8080
          predicates:
            - Path=/hairShopManagementSystems/** /reservationStatuses/**
        - id: CustomerCare
          uri: http://CustomerCare:8080
          predicates:
            - Path= 
        - id: HRSystem
          uri: http://HRSystem:8080
          predicates:
            - Path=/hrSystems/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
